name = "CavityTools"
uuid = "217fe2f1-7e3d-419f-9934-cd6900c2759a"
authors = ["Alfredo Braunstein <alfredo.braunstein@polito.it> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
